### ISSUE TITLE
Reporte de Diagrama de Secuencia 

### ISSUE THREAD

**Issue by JazminloRI** [SistemasTecTlaxiaco/practica-de-diagrama-de-secuencia-equipo-bjy#1]
[Diagrama de Secuencia - U4.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-diagrama-de-secuencia-equipo-bjy/files/7830954/Diagrama.de.Secuencia.-.U4.pdf)

**Comment by KarlaV0** [comment]
30%

**Comment by josealfredo79** [comment]
Los parametros hacen falta agregar a los métodos o mensajes

**Comment by josealfredo79** [comment]
Revisado
